{{- if .Values.roleBinding.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBinding.name }}
  labels:
    {{- include "ep-digital-common.labels" . | nindent 4 }}
  {{- with .Values.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  kind: Role
  name: {{ .Values.role.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "ep-digital-common.serviceAccountName" . }}
{{- end }}