apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualService.name }}
spec:
  hosts:
    - "{{ .Values.istio.host }}"
  gateways:
    {{- range .Values.istio.gateway }}
    - "{{ . }}"
    {{- end }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.istio.virtualService.path }}
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
          weight: 100
      corsPolicy:
        allowOrigins:
          {{- $allowOrigin := .Values.istio.allowOrigin | default (list) }}
          {{- $allowOrigins := .Values.istio.allowOrigins | default (list) }}
          {{- $mergedOrigins := append $allowOrigin $allowOrigins | uniq }}
          {{- range $mergedOrigins }}
          - exact: "{{ . }}"
          {{- end }}
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - PATCH
        allowHeaders:
          - access-control-allow-origin
        allowCredentials: false
        maxAge: "24h"
        
