{{- $shouldCreateSA := or .Values.vaultInjector.enabled .Values.serviceAccount.enabled }}
{{- if $shouldCreateSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ep-digital-common.serviceAccountName" . }}
  labels:
    {{- include "ep-digital-common.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}